name: "Godot Android Export"

on:
  push:
    branches:
      - main
      - master

jobs:
  export:
    name: Android Export
    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci:4.2.2
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Extract Zip File
        run: |
          if [ -f "Roblox2_Online_v1_2.zip" ]; then
            unzip -o Roblox2_Online_v1_2.zip
          fi

      - name: Setup Keystore & Config
        run: |
          mkdir -p /root/.android
          keytool -keyalg RSA -genkeypair -alias androiddebugkey -keypass android -keystore /root/.android/debug.keystore -storepass android -dname "CN=Android Debug,O=Android,C=US" -validity 9999
          
          PROJ_DIR=$(find . -name "project.godot" -exec dirname {} \;)
          cat <<EOF > "$PROJ_DIR/export_presets.cfg"
          [preset.0]

          name="Android"
          platform="Android"
          runnable=true
          dedicated_server_id=""
          custom_features=""
          export_filter="all_resources"
          include_filter=""
          exclude_filter=""
          export_path="../build/android/Roblox2_Online.apk"
          encryption_include_filters=""
          encryption_exclude_filters=""
          encrypt_pck=false
          encrypt_directory=false

          [preset.0.options]

          custom_template/release=""
          custom_template/debug=""
          gradle_build/use_gradle_build=false
          architectures/armeabi-v7a=true
          architectures/arm64-v8a=true
          architectures/x86=false
          architectures/x86_64=false
          package/unique_name="com.example.roblox2"
          package/name="Roblox2 Online"
          package/signed=false
          keystore/debug="/root/.android/debug.keystore"
          keystore/debug_user="androiddebugkey"
          keystore/debug_password="android"
          EOF

      - name: Export APK
        run: |
          mkdir -v -p build/android
          PROJ_DIR=$(find . -name "project.godot" -exec dirname {} \;)
          
          # Container icindeki resmi template dosyalarini bagla
          mkdir -p /root/.local/share/godot/export_templates/4.2.2.stable
          cp -r /root/.local/share/godot/templates/4.2.2.stable/* /root/.local/share/godot/export_templates/4.2.2.stable/ 2>/dev/null || true

          cd "$PROJ_DIR"
          godot --headless --export-release "Android" ../build/android/Roblox2_Online.apk

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Android-APK
          path: build/android/Roblox2_Online.apk
