name: "Godot Android Export"

on:
  push:
    branches:
      - main
      - master

jobs:
  export:
    name: Android Export
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Extract Zip File
        run: |
          if [ -f "Roblox2_Online_v1_2.zip" ]; then
            unzip -o Roblox2_Online_v1_2.zip
          fi

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Generate export_presets.cfg
        run: |
          PROJ_DIR=$(find . -name "project.godot" -exec dirname {} \;)
          cat <<EOF > "$PROJ_DIR/export_presets.cfg"
          [preset.0]

          name="Android"
          platform="Android"
          runnable=true
          dedicated_server_id=""
          custom_features=""
          export_filter="all_resources"
          include_filter=""
          exclude_filter=""
          export_path="build/android/Roblox2_Online.apk"
          encryption_include_filters=""
          encryption_exclude_filters=""
          encrypt_pck=false
          encrypt_directory=false

          [preset.0.options]

          custom_template/release=""
          custom_template/debug=""
          gradle_build/use_gradle_build=false
          architectures/armeabi-v7a=true
          architectures/arm64-v8a=true
          architectures/x86=false
          architectures/x86_64=false
          package/unique_name="com.example.roblox2"
          package/name="Roblox2 Online"
          package/signed=false
          EOF

      - name: Godot Android Export Action
        uses: firebelley/godot-export@v5.2.1
        with:
          godot_executable_download_url: https://downloads.tuxfamily.org/godotengine/4.2.2/Godot_v4.2.2-stable_linux.x86_64.zip
          godot_export_templates_download_url: https://downloads.tuxfamily.org/godotengine/4.2.2/Godot_v4.2.2-stable_export_templates.tpz
          relative_project_path: ./Roblox2_Online_v1_2/godot
          archive_output: false

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Android-APK
          path: /home/runner/.local/share/godot/builds/Android/
